//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NClass.AssemblyImport.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NClass.AssemblyImport.Lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to class.
        /// </summary>
        internal static string Element_Class {
            get {
                return ResourceManager.GetString("Element_Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constant.
        /// </summary>
        internal static string Element_Constant {
            get {
                return ResourceManager.GetString("Element_Constant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to constructor.
        /// </summary>
        internal static string Element_Constructor {
            get {
                return ResourceManager.GetString("Element_Constructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delegate.
        /// </summary>
        internal static string Element_Delegate {
            get {
                return ResourceManager.GetString("Element_Delegate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to elements.
        /// </summary>
        internal static string Element_Elements {
            get {
                return ResourceManager.GetString("Element_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enum.
        /// </summary>
        internal static string Element_Enum {
            get {
                return ResourceManager.GetString("Element_Enum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum value.
        /// </summary>
        internal static string Element_EnumValue {
            get {
                return ResourceManager.GetString("Element_EnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event.
        /// </summary>
        internal static string Element_Event {
            get {
                return ResourceManager.GetString("Element_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to field.
        /// </summary>
        internal static string Element_Field {
            get {
                return ResourceManager.GetString("Element_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interface.
        /// </summary>
        internal static string Element_Interface {
            get {
                return ResourceManager.GetString("Element_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to method.
        /// </summary>
        internal static string Element_Method {
            get {
                return ResourceManager.GetString("Element_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        internal static string Element_Operator {
            get {
                return ResourceManager.GetString("Element_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to property.
        /// </summary>
        internal static string Element_Property {
            get {
                return ResourceManager.GetString("Element_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to struct.
        /// </summary>
        internal static string Element_Struct {
            get {
                return ResourceManager.GetString("Element_Struct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load assembly since it seems to be not an assembly....
        /// </summary>
        internal static string Error_BadImageFormat {
            get {
                return ResourceManager.GetString("Error_BadImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while importing!
        ///
        ///{0}
        ///
        ///Note: Assemblys which are created with a fuscator might fail to import..
        /// </summary>
        internal static string Error_GeneralException {
            get {
                return ResourceManager.GetString("Error_GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_MessageBoxTitle {
            get {
                return ResourceManager.GetString("Error_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open assembly due to missing referenced assemblies..
        /// </summary>
        internal static string Error_MissingReferencedAssemblies {
            get {
                return ResourceManager.GetString("Error_MissingReferencedAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assembly file to import..
        /// </summary>
        internal static string Error_NoAssembly {
            get {
                return ResourceManager.GetString("Error_NoAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Import an assembly....
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET assembly importer by Malte Ried.
        /// </summary>
        internal static string Menu_ToolTip {
            get {
                return ResourceManager.GetString("Menu_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        internal static string Modifier_All {
            get {
                return ResourceManager.GetString("Modifier_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        internal static string Modifier_Default {
            get {
                return ResourceManager.GetString("Modifier_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instance.
        /// </summary>
        internal static string Modifier_Instance {
            get {
                return ResourceManager.GetString("Modifier_Instance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal.
        /// </summary>
        internal static string Modifier_Internal {
            get {
                return ResourceManager.GetString("Modifier_Internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private.
        /// </summary>
        internal static string Modifier_Private {
            get {
                return ResourceManager.GetString("Modifier_Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected.
        /// </summary>
        internal static string Modifier_Protected {
            get {
                return ResourceManager.GetString("Modifier_Protected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protected internal.
        /// </summary>
        internal static string Modifier_ProtectedInternal {
            get {
                return ResourceManager.GetString("Modifier_ProtectedInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public.
        /// </summary>
        internal static string Modifier_Public {
            get {
                return ResourceManager.GetString("Modifier_Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to static.
        /// </summary>
        internal static string Modifier_Static {
            get {
                return ResourceManager.GetString("Modifier_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies (*.exe, *.dll)|*.exe;*.dll.
        /// </summary>
        internal static string OpenFileDialog_Filter {
            get {
                return ResourceManager.GetString("OpenFileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Settings_CancelButton {
            get {
                return ResourceManager.GetString("Settings_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Associations.
        /// </summary>
        internal static string Settings_CreateAssociations {
            get {
                return ResourceManager.GetString("Settings_CreateAssociations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Generalizations.
        /// </summary>
        internal static string Settings_CreateGeneralizations {
            get {
                return ResourceManager.GetString("Settings_CreateGeneralizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a label on the side of the aggregation.
        /// </summary>
        internal static string Settings_CreateLabel {
            get {
                return ResourceManager.GetString("Settings_CreateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create nesting Relationships.
        /// </summary>
        internal static string Settings_CreateNesting {
            get {
                return ResourceManager.GetString("Settings_CreateNesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Realizations.
        /// </summary>
        internal static string Settings_CreateRealizations {
            get {
                return ResourceManager.GetString("Settings_CreateRealizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Relationships.
        /// </summary>
        internal static string Settings_CreateRelationships {
            get {
                return ResourceManager.GetString("Settings_CreateRelationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&lt;&apos; is not allowed.
        /// </summary>
        internal static string Settings_Error_AngleBracketNotAllowed {
            get {
                return ResourceManager.GetString("Settings_Error_AngleBracketNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a name.
        /// </summary>
        internal static string Settings_Error_NoTemplateName {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a template first.
        /// </summary>
        internal static string Settings_Error_NoTemplateSelected {
            get {
                return ResourceManager.GetString("Settings_Error_NoTemplateSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This template can&apos;t be deleted.
        /// </summary>
        internal static string Settings_Error_TemplateCantBeDeleted {
            get {
                return ResourceManager.GetString("Settings_Error_TemplateCantBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import everything except.
        /// </summary>
        internal static string Settings_Filter_BlackList {
            get {
                return ResourceManager.GetString("Settings_Filter_BlackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Settings_Filter_ElementColumnTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_ElementColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string Settings_Filter_GroupTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_GroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        internal static string Settings_Filter_ModifierColumnTitle {
            get {
                return ResourceManager.GetString("Settings_Filter_ModifierColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import only the folowing.
        /// </summary>
        internal static string Settings_Filter_WhiteList {
            get {
                return ResourceManager.GetString("Settings_Filter_WhiteList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Settings_OKButton {
            get {
                return ResourceManager.GetString("Settings_OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove fields which constructs the aggregation (code generation won&apos;t produce any code for that aggregation).
        /// </summary>
        internal static string Settings_RemoveFields {
            get {
                return ResourceManager.GetString("Settings_RemoveFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string Settings_Template {
            get {
                return ResourceManager.GetString("Settings_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Settings_Template_DeleteButton {
            get {
                return ResourceManager.GetString("Settings_Template_DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;last used&gt;.
        /// </summary>
        internal static string Settings_Template_LastUsed {
            get {
                return ResourceManager.GetString("Settings_Template_LastUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Settings_Template_LoadButton {
            get {
                return ResourceManager.GetString("Settings_Template_LoadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store.
        /// </summary>
        internal static string Settings_Template_StoreButton {
            get {
                return ResourceManager.GetString("Settings_Template_StoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some unsafe types exist at the imported assembly. Every element using such a type isn&apos;t imported..
        /// </summary>
        internal static string UnsafeTypesPresent {
            get {
                return ResourceManager.GetString("UnsafeTypesPresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningTitle {
            get {
                return ResourceManager.GetString("WarningTitle", resourceCulture);
            }
        }
    }
}
